#!/bin/bash

set -e

name="streamer_wands"
version="$(jq -r '.version' package.json)"
sha="$(git rev-parse --short HEAD)"

git -c core.autocrlf=false archive --prefix="$name/" -o "releases/$name--$version+$sha".zip HEAD:mod