#!/bin/bash

set -e

name="streamer_wands"
version="$(jq -r '.modVersion' package.json)"
if [ -n "$DEV" ]; then
  version="$version+$(git rev-parse --short HEAD)"
fi

git -c core.autocrlf=false archive --prefix="$name/" -o "releases/$name--$version".zip HEAD:mod